version: '3'
services:
    node_app:
        container_name: node_app
        build: .
        command: npm run dev
        ports:
            - "3333:3333"
        volumes:
            - .:/usr/app
        networks:
            - default

    postgres:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        tty: true
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: apivendas
        networks:
            - default
        volumes:
            - ./docker/postgres:/var/lib/postgresql

networks:
    default:
        driver: bridge

